# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'devuser' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'devuser' } %>
  database: <%= ENV.fetch('DATABASE_NAME') { 'mafelerdb' } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('TEST_DATABASE_NAME') { 'test_mafelerdb' } %>

production:
  <<: *default

